# Generated by Django 3.1.4 on 2021-01-31 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_auto_20210131_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
