# Generated by Django 3.1.4 on 2021-01-31 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_remove_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='consumer.brand'),
        ),
    ]
