# Generated by Django 3.1.4 on 2021-01-31 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0004_product_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
