# Generated by Django 3.1.6 on 2021-02-19 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0007_auto_20210218_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='consumer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consumer.customuser'),
            preserve_default=False,
        ),
    ]
