# Generated by Django 3.1.6 on 2021-02-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0008_address_consumer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address Book'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'World Currencies'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(default='Home', max_length=80),
            preserve_default=False,
        ),
    ]
