# Generated by Django 3.1.6 on 2021-02-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210131_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_item',
            field=models.ManyToManyField(to='order.CartItem'),
        ),
    ]
